### ISSUE TITLE
Compatibility with ZNC 1.6

### ISSUE THREAD

**Issue by ticklemynausea** [dctrwatson/znc-fish#12]
znc-buildmod fails with the message:

```
Building "fish.so" for ZNC 1.6.0... fish.cpp: In member function ‘virtual CModule::EModRet CFishMod::OnUserMsg(CString&, CString&)’:
fish.cpp:332:62: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’
fish.cpp: In member function ‘virtual CModule::EModRet CFishMod::OnUserAction(CString&, CString&)’:
fish.cpp:365:62: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’
fish.cpp: In member function ‘virtual CModule::EModRet CFishMod::OnUserNotice(CString&, CString&)’:
fish.cpp:398:62: error: invalid initialization of reference of type ‘std::vector<CClient*>&’ from expression of type ‘const std::vector<CClient*>’
[ !! ] Error while building "fish.so"
```

Are there any plans for a new version?

**Comment by ticklemynausea** [comment]
https://github.com/dctrwatson/znc-fish/pull/10/commits

this pull request seems to fix the issues

**Comment by philicious** [comment]
I didnt diff this repos fish.cpp nor the PR, but I can report that http://pastebin.com/K8zvJ89v (which is linked on http://wiki.znc.in/Fish as "For 1.4 and newer try this one"), is working fine with znc 1.6.3

just leaving this message for other people coming by
